



filein( getFilenamePath(getSourceFileName()) + "/includes.ms" )	--"./includes.ms"

filein( getFilenamePath(getSourceFileName()) + "/Lib/PhaseCreator/PhaseCreator.ms" )	--"./Lib/PhaseCreator/PhaseCreator.ms"

filein( getFilenamePath(getSourceFileName()) + "/PhaseMaker/CreatePhaseMakerDialog.ms" )	--"./PhaseMaker/CreatePhaseMakerDialog.ms"

/*------------------------------------------------------------------------------
	CREATE DIALOG
--------------------------------------------------------------------------------*/

createPhaseMakerDialog()
