



filein( getFilenamePath(getSourceFileName()) + "/main_script.ms" )	--"./main_script.ms"

filein( getFilenamePath(getSourceFileName()) + "/Lib/PhaseCreator/PhaseCreator.ms" )	--"./Lib/PhaseCreator/PhaseCreator.ms"

filein( getFilenamePath(getSourceFileName()) + "/PhaseMaker/CreatePhaseMakerDialog.ms" )	--"./PhaseMaker/CreatePhaseMakerDialog.ms"

/*------------------------------------------------------------------------------
	CREATE DIALOG
--------------------------------------------------------------------------------*/

createPhaseMakerDialog()
