
filein( getFilenamePath(getSourceFileName()) + "/includes.ms" )	--"./includes.ms"

filein( getFilenamePath(getSourceFileName()) + "/TrackbarTools/frameButtonRcMenu/frameButtonRcMenu.ms" )	--"./TrackbarTools/frameButtonRcMenu/frameButtonRcMenu.ms"

filein( getFilenamePath(getSourceFileName()) + "/TrackbarTools/trackbarDialogTicker/trackbarDialogTicker.ms" )	--"./TrackbarTools/trackbarDialogTicker/trackbarDialogTicker.ms"

filein( getFilenamePath(getSourceFileName()) + "/TrackbarTools/TrackbarToolsCallback/TrackbarToolsCallback.ms" )	--"./TrackbarTools/TrackbarToolsCallback/TrackbarToolsCallback.ms"

filein( getFilenamePath(getSourceFileName()) + "/TrackbarTools/trackbarToolsDialog.ms" )	--"./TrackbarTools/trackbarToolsDialog.ms"


/*------------------------------------------------------------------------------
	CREATE DIALOG
--------------------------------------------------------------------------------*/
trackbarToolsDialog()