
filein( getFilenamePath(getSourceFileName()) + "/../AnimKeyTools.ms" )	--"./../AnimKeyTools.ms"

filein( getFilenamePath(getSourceFileName()) + "/PhaseCreator/PhaseCreator.ms" )	--"./PhaseCreator/PhaseCreator.ms"

filein( getFilenamePath(getSourceFileName()) + "/PhaseMaker/CreatePhaseMakerDialog.ms" )	--"./PhaseMaker/CreatePhaseMakerDialog.ms"


/*------------------------------------------------------------------------------
	CREATE DIALOG
--------------------------------------------------------------------------------*/

createPhaseMakerDialog()
